name: 'GitHub Push'
description: 'Push a directory to github.'
author: 'Tarocch1'

inputs:
  token:
    description: 'Token for the repo.'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Repository name to push.'
    required: false
    default: ${{ github.repository }}
  branch:
    description: 'Destination branch to push.'
    required: false
    default: ''
  directory:
    description: 'Directory to push.'
    required: true
  sha:
    description: 'Whether to add sha at the end of commit.'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Clone
      shell: bash
      run: ${{ github.action_path }}/clone.sh
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_BRANCH: ${{ inputs.branch }}
    - name: Push
      shell: bash
      run: ${{ github.action_path }}/push.sh
      env:
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_SHA: ${{ inputs.sha }}
    - name: Clean
      shell: bash
      run: ${{ github.action_path }}/clean.sh
