name: "ossutil"
description: "Use aliyun ossutil."
author: "Tarocch1"

inputs:
  keyid:
    description: "Aliyun keyID."
    required: true
  secret:
    description: "Aliyun secret."
    required: true
  region:
    description: "Aliyun region."
    required: false
    default: cn-hongkong
  args:
    description: "Args for ossutil."
    required: true

runs:
  using: "composite"
  steps:
    - name: install
      shell: bash
      run: |
        set -e
        bash ${{ github.action_path }}/install.sh
    - name: ossutil
      shell: bash
      env:
        OSS_ACCESS_KEY_ID: ${{ inputs.keyid }}
        OSS_ACCESS_KEY_SECRET: ${{ inputs.secret }}
        OSS_REGION: ${{ inputs.region }}
      run: |
        set -e
        ossutil ${{ inputs.args }}
