name: "ossutil"
description: "Use aliyun ossutil."
author: "Tarocch1"

inputs:
  keyid:
    description: "Aliyun keyID."
    required: true
  secret:
    description: "Aliyun secret."
    required: true
  region:
    description: "Aliyun region."
    required: false
    default: cn-hongkong
  args:
    description: "Args for ossutil."
    required: true

runs:
  using: "composite"
  steps:
    - name: install
      shell: bash
      run: |
        set -e
        curl -o /tmp/ossutil-2.1.0-linux-amd64.zip https://gosspublic.alicdn.com/ossutil/v2/2.1.0/ossutil-2.1.0-linux-amd64.zip
        unzip -d /tmp /tmp/ossutil-2.1.0-linux-amd64.zip
        cp /tmp/ossutil-2.1.0-linux-amd64/ossutil /usr/local/bin/
        chmod 755 /usr/local/bin/ossutil
    - name: ossutil
      shell: bash
      env:
        OSS_ACCESS_KEY_ID: ${{ inputs.keyid }}
        OSS_ACCESS_KEY_SECRET: ${{ inputs.secret }}
        OSS_REGION: ${{ inputs.region }}
      run: |
        set -e
        ossutil ${{ inputs.args }}
